prompts:
  - "photo of a storage bin under warm sodium lights, realistic texture"
  - "industrial shelf bin with mixed metallic hardware, cinematic lighting"
  - "factory workstation bin illuminated by cool LEDs, photorealistic"
  - "warehouse storage tote in diffuse daylight, true-to-life materials"
